sudo: required

language: golang

services:
  - docker

script:
  - docker build -t yakkodash/restful_ifconfig:latest .

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push yakkodash/restful_ifconfig;
      fi
